import { expect, test } from "vitest";
import path from "path";
import { logger } from "../utils/logger";
import { deleteDLinkConfig, getDLinkConfig } from "../fn";
import { join } from "path";
import compressUtils from "./compressUtils";
let examplesDIR = join(__dirname, "examples");
let distDIR = join(__dirname, "dist");
import fs from "fs";
import { computeHash } from "./hash";
