name: Build

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.21

    - name: Get dependencies
      run: go mod download

    - name: Run build script
      run: |
        npm i -g pnpm 
        npm i -g typescript
        cd ./sub/web
        pnpm install
        cd ../../
        cd ./pipeline
        chmod +x ./build-all.sh
        ./build-all.sh